services:
  qbittorrent:
    container_name: qbittorrent
    image: trigus42/qbittorrentvpn:latest
    cap_add:
    - NET_ADMIN
    sysctls:
    - net.ipv4.conf.all.src_valid_mark=1
    privileged: true
    ports:
      - 80:8080
    volumes:
      - ./:/config
      - ${MEDIA_DIR:?err}/torrents:/data/torrents:rw
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.middlewares: auth@file   # enabling authelia security login
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080   # load balancing the port with traefik dashboard
    environment:
      TZ: America/Vancouver
      PGID: ${PGID:?err}
      PUID: ${PUID:?err}
      UMASK: ${UMASK:?err}
      VPN_ENABLED: yes
      VPN_TYPE: openvpn
      VPN_USERNAME: ${VPN_USERNAME}
      VPN_PASSWORD: ${VPN_PASSWORD}
      WEBUI_PASSWORD: ${MY_WEBUI_PASSWORD}
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  proxy:
    external: true
