version: '3.9'
services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    expose:
      - 7878
    volumes:
      - ${APP_DIR:?err}/radarr:/config
      - ${MEDIA_DIR:?err}:/data
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.entryPoints: https
      traefik.http.routers.radarr.middlewares: auth@file

      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: ${CONTAINER_TIME_ZONE:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
      UMASK: ${UMASK:?err}
    networks:
      - proxy
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    expose:
      - 8989
    volumes:
      - ${APP_DIR:?err}/sonarr:/config
      - ${MEDIA_DIR:?err}:/data
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.entryPoints: https
      traefik.http.routers.sonarr.middlewares: auth@file

      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: ${CONTAINER_TIME_ZONE:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
      UMASK: ${UMASK:?err}
    networks:
      - proxy
    restart: unless-stopped
    
  qbittorrent:
    container_name: qbittorrent
    image: dyonr/qbittorrentvpn:latest
    cap_add:
    - NET_ADMIN
    privileged: true
    expose:
      - 8080
    ports:
      - 8999:8999
      - 8999:8999/udp
    volumes:
      - ${APP_DIR:?err}/qbittorrent:/config
      - ${MEDIA_DIR:?err}/torrents:/data/torrents:rw
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.entryPoints: https
      traefik.http.routers.qbittorrent.middlewares: auth@file
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080

      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: ${CONTAINER_TIME_ZONE:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
      UMASK: ${UMASK:?err}
      VPN_ENABLED: yes
      VPN_TYPE: openvpn
      VPN_USERNAME: ${VPN_USERNAME}
      VPN_PASSWORD: ${VPN_PASSWORD}
      LAN_NETWORK: 192.168.0.0/24, 172.18.0.0/24
    networks:
      - proxy
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    expose:
      - 9696
    volumes:
      - ${APP_DIR:?err}/prowlarr:/config
    labels:
      traefik.enable: true
      traefik.http.routers.jackett.entryPoints: https
      traefik.http.routers.jackett.middlewares: auth@file

      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: ${CONTAINER_TIME_ZONE:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
    networks:
      - proxy 
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true
