version: '3.9'
services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    expose:
      - 7878
    volumes:
      - ./radarr:/config
      - ${MEDIA_DIR:?err}:/data
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.entryPoints: https
      traefik.http.routers.radarr.middlewares: auth@file

      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: America/Vancouver
      PGID: ${ID:?err}
      PUID: ${ID:?err}
      UMASK: ${UMASK:?err}
    networks:
      - proxy
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    expose:
      - 8989
    volumes:
      - ./sonarr:/config
      - ${MEDIA_DIR:?err}:/data
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.entryPoints: https
      traefik.http.routers.sonarr.middlewares: auth@file

      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: America/Vancouver
      PGID: ${ID:?err}
      PUID: ${ID:?err}
      UMASK: ${UMASK:?err}
    networks:
      - proxy
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    expose:
      - 9696
    volumes:
      - ./prowlarr:/config
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.entryPoints: https
      traefik.http.routers.prowlarr.middlewares: auth@file

      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: America/Vancouver
      PGID: ${ID:?err}
      PUID: ${ID:?err}
    networks:
      - proxy
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    expose:
      - 6767
    volumes:
      - ./bazarr:/config
      - ${MEDIA_DIR:?err}:/data
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.entryPoints: https
      traefik.http.routers.bazarr.middlewares: auth@file

      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: America/Vancouver
      PGID: ${ID:?err}
      PUID: ${ID:?err}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true
