x-app: &default
  restart: unless-stopped
  networks:
    -  proxy
  environment:
    TZ: America/Vancouver
    PGID: ${PGID:?err}
    PUID: ${PUID:?err}
    UMASK: ${UMASK:?err}
  labels: &labels
    traefik.enable: true
    com.centurylinklabs.watchtower.enable: true
  security_opt:
    - no-new-privileges:true

services:
  radarr:
    <<: *default
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    expose:
      - 7878
    volumes:
      - ./radarr:/config
      - ${MEDIA_DIR:?err}:/data
    labels:
      <<: *labels
      traefik.http.routers.radarr.middlewares: auth@file

  sonarr:
    <<: *default
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    expose:
      - 8989
    volumes:
      - ./sonarr:/config
      - ${MEDIA_DIR:?err}:/data
    labels:
      <<: *labels
      traefik.http.routers.sonarr.middlewares: auth@file

  prowlarr:
    <<: *default
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    expose:
      - 9696
    volumes:
      - ./prowlarr:/config
    labels:
      <<: *labels
      traefik.http.routers.prowlarr.middlewares: auth@file

  notifiarr:
    <<: *default
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr:latest
    expose:
      - 5454
    volumes:
      - ./notifiarr:/config
      - /var/run/utmp:/var/run/utmp
    labels:
      <<: *labels
      traefik.http.routers.notifiarr.middlewares: auth@file

  flaresolverr:
    <<: *default
    container_name: flaresolverr
    hostname: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    expose:
      - 8191
    labels:
      <<: *labels
      traefik.http.routers.flaresolverr.middlewares: auth@file

networks:
  proxy:
    external: true
