version: '3.9'
services:
  auth:
    container_name: authelia
    image: authelia/authelia:latest
    expose:
      - 9091
    volumes:
      - ${APP_DIR:?err}/authelia:/etc/authelia/config
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.entryPoints: https
      traefik.http.routers.authelia.rule: Host(`auth.${DOMAIN:?err}`)

      # Watchtower Update
      com.centurylinklabs.watchtower.enable: true
    networks:
      - proxy
      - secure
    restart: unless-stopped
    depends_on:
      - redis
      - mariadb

  redis:
    container_name: redis
    image: bitnami/redis:latest
    expose:
      - 6379
    volumes:
      - ${APP_DIR:?err}/authelia/redis:/redis/bitnami/
    labels:
      # Watchtower Update
      com.centurylinklabs.watchtower.enable: true
    environment:
      REDIS_PASSWORD: ${REDIS_PASS:?err}
    networks:
      - secure
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb:latest
    expose:
      - 3306
    volumes:
      - ${APP_DIR:?err}/authelia/mariadb:/etc/mariadb/config
    labels:
      # Watchtower Update
      com.centurylinklabs.watchtower.enable: true
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS:?err}
    networks:
      - secure
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true
  secure:
    driver: bridge
    external: true
