version: '3.9'
services:
  auth:
    container_name: auth
    image: authelia/authelia:latest
    expose:
      - 9091
    volumes:
      - ${APP_DIR:?err}/authelia/config:/config
      - ${APP_DIR:?err}/authelia/secrets:/secrets
    labels:
      traefik.enable: true
      traefik.http.routers.auth.entryPoints: https

      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: ${CONTAINER_TIME_ZONE}
      PUID: ${PUID}
      PGID: ${PGID}
      AUTHELIA_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /secrets/LDAP_ADMIN_PASSWORD
      AUTHELIA_SESSION_SECRET_FILE: /secrets/SESSION_SECRET
      AUTHELIA_SESSION_REDIS_PASSWORD_FILE: /secrets/REDIS_PASS
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/STORAGE_ENCRYPTION_KEY
      AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE: /secrets/STORAGE_PASSWORD
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /secrets/SMTP_PASSWORD
    networks:
      - proxy
      - secure
    restart: unless-stopped
    depends_on:
      - redis
      - mariadb

  redis:
    container_name: redis
    image: bitnami/redis:latest
    expose:
      - 6379
    volumes:
      - ${APP_DIR:?err}/authelia/redis:/redis/bitnami/
      - ${APP_DIR:?err}/authelia/secrets:/secrets
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: ${CONTAINER_TIME_ZONE}
      REDIS_PASSWORD_FILE: /secrets/REDIS_PASSWORD
    networks:
      - secure
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: mariadb
    expose:
      - 3306
    volumes:
      - ${APP_DIR:?err}/authelia/mariadb:/config
      - ${APP_DIR:?err}/authelia/secrets:/secrets
    environment:
      TZ: ${CONTAINER_TIME_ZONE}
      MYSQL_ROOT_PASSWORD_FILE: /secrets/MYSQL_ROOT_PASSWORD
    networks:
      - secure
    restart: unless-stopped

  openldap:
    container_name: openldap
    image: osixia/openldap:latest
    expose:
      - 389
      - 636
    volumes:
      - ${APP_DIR:?err}/authelia/openldap/certificates:/container/service/slapd/assets/certs
      - ${APP_DIR:?err}/authelia/openldap/slapd/database:/var/lib/ldap
      - ${APP_DIR:?err}/authelia/openldap/slapd/config:/etc/ldap/slapd.d
      - ${APP_DIR:?err}/authelia/secrets:/secrets
    environment:
      TZ: ${CONTAINER_TIME_ZONE}
      LDAP_ORGANISATION: "${LDAP_ORGANISATION:?err}"
      LDAP_DOMAIN: "${LDAP_DOMAIN:?err}"
      LDAP_BASE_DN: "${LDAP_BASE_DN:?err}"
      LDAP_TLS_CRT_FILENAME: "${LDAP_TLS_CRT_FILENAME:?err}"
      LDAP_TLS_KEY_FILENAME: "${LDAP_TLS_KEY_FILENAME:?err}"
      LDAP_TLS_CA_CRT_FILENAME: "${LDAP_TLS_CA_CRT_FILENAME:?err}"
      LDAP_ADMIN_USERNAME: "${LDAP_ADMIN_USERNAME:?err}"
      LDAP_ADMIN_PASSWORD_FILE: /secrets/LDAP_ADMIN_PASSWORD
      LDAP_CONFIG_PASSWORD_FILE: /secrets/LDAP_CONFIG_PASSWORD
      LDAP_RFC2307BIS_SCHEMA: 'true'

      com.centurylinklabs.watchtower.enable: true  
    networks:
      - secure
    restart: unless-stopped

  ldapadmin:
    container_name: ldapadmin
    image: osixia/phpldapadmin:latest
    expose:
      - 80
    labels:
      traefik.enable: true
      traefik.http.routers.ldapadmin.entryPoints: https
      traefik.http.routers.ldapadmin.middlewares: auth@file
    environment:
      TZ: ${CONTAINER_TIME_ZONE}
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: false

      com.centurylinklabs.watchtower.enable: true
    volumes:
     - ${APP_DIR:?err}/authelia/openldap/admin:/var/www/phpldapadmin   # used to make edits to the config file
    depends_on:
      - openldap
    networks:
      - proxy
      - secure
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true
  secure:
    driver: bridge
    external: true
