version: '3.9'
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
      - 8080:8080  # traefik drashboard port
    volumes:
      - ./:/etc/traefik/
      - ./secrets:/secrets
    networks:
      - proxy   # change to your docker network name
      - secure  # have a second one for sensitive containers
    labels:
      traefik.enable: true   # Enable Traefik reverse proxy
      traefik.http.routers.api.entryPoints: https    # Set the Traefik entry point.
      traefik.http.routers.api.service: api@internal    # Enable Traefik API.
      traefik.http.routers.api.middlewares: auth@file  # enabling authelia login to traefik

      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: America/Vancouver
      PORKBUN_API_KEY_FILE: /secrets/PORKBUN_API_KEY
      PORKBUN_SECRET_API_KEY_FILE: /secrets/PORKBUN_SECRET_API_KEY
    restart: unless-stopped
    depends_on:
      - socket-proxy

  socket-proxy:
    container_name: traefik-socket-proxy
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: ${CONTAINER_TIME_ZONE:?err}
      CONTAINERS: 1
      POST: 0
    privileged: true
    networks:
      - secure
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true

  secure:
    driver: bridge
    external: true
