version: '3.9'
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
      - 8080:8080  # traefik drashboard port
    volumes:
      - ${APP_DIR:?err}/traefik/:/etc/traefik/
    networks:
      - proxy   # change to your docker network name
    labels:
      traefik.enable: true   # Enable Traefik reverse proxy for the Traefik dashboard.
      traefik.http.routers.api.rule: Host(`traefik.${DOMAIN:?err}`)    # Define the subdomain for the traefik dashboard.
      traefik.http.routers.api.entryPoints: https    # Set the Traefik entry point.
      traefik.http.routers.api.service: api@internal    # Enable Traefik API.

      # Watchtower Update
      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: ${CONTAINER_TIME_ZONE:?err}
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN:?err}
    restart: unless-stopped
    depends_on:
      - socket-proxy

  socket-proxy:
    container_name: traefik-socket-proxy
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy   # change to your docker network name
    environment:
      TZ: ${CONTAINER_TIME_ZONE:?err}
      CONTAINERS: 1
    privileged: true
    restart: unless-stopped
    labels:
      # Watchtower update
      com.centurylinklabs.watchtower.enable: true

networks:
  proxy:   # defining your docker network name
    driver: bridge
    external: true
