global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: :443
    http:
      tls:
        # Generate a wildcard domain certificate
        certResolver: letsencrypt
        domains:
          - main: ${DOMAIN:?err}.com
            sans:
              - '*.${DOMAIN:?err}.COM'
      middlewares:
        - securityHeaders@file


providers:
  providersThrottleDuration: 2s

  # docker provider for connecting all apps that are inside your docker network
  docker:
    watch: true
    network: proxy   # change to your docker network name
    # Default host rule to containername.domain.example
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.${DOMAIN}.COM`)"
    endpoint: "tcp://socket-proxy:2375"
    swarmModeRefreshSeconds: 15s
    exposedByDefault: false

  # all the traefik rules that will be run in the directory
  file:
    filename: /etc/traefik/fileConfig.yml
    watch: true

# Using LetsEncrypt to generate ssl certs
certificatesResolvers:
  mydnschallenge:
    acme:
      email: ${USER_EMAIL:?err}
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        # Used to make sure the dns challenge is propagated to the rights dns servers
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        delayBeforeCheck: 10

# Enabling traefik dashboard UI
api:
  dashboard: false
  insecure: true

# log level INFO|DEBUG|ERROR
log:
  level: INFO
