global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  # Not used in apps, but redirect everything from HTTP to HTTPS
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  # HTTPS enpoint, with domain wildcard
  https:
    address: :443
    http:
      tls:
        # Generate a wildcard domain certificate
        certResolver: letsencrypt
        domains:
          - main: deemedia.duckdns.org   # change to your domain
            sans:
              - '*.deemedia.duckdns.org' # change to your domain
      middlewares:
        - securityHeaders@file


providers:
  providersThrottleDuration: 2s

  # docker provider for connecting all apps that are inside your docker network
  docker:
    watch: true
    network: proxy   # change to your docker network name
    # Default host rule to containername.domain.example
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.deemedia.duckdns.org`)" # replace with your domain
    endpoint: "tcp://socket-proxy:2375"
    swarmModeRefreshSeconds: 15s
    exposedByDefault: false

  # all the traefik rules that will be run in the directory
  file:
    filename: /etc/traefik/fileConfig.yml
    watch: true

# Using LetsEncrypt to generate ssl certs
certificatesResolvers:
  letsencrypt:
    acme:
      email: dliew08@gmail.com
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: duckdns
        # Used to make sure the dns challenge is propagated to the rights dns servers
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
        delayBeforeCheck: 10

# Enabling traefik dashboard UI
api:
  dashboard: true
  insecure: true

# log level INFO|DEBUG|ERROR
log:
  level: INFO
