global:
  checkNewVersion: true

entryPoints:
  http:
    address: :80

  https:
    address: :443

providers:
  providersThrottleDuration: 2s

  # docker provider for connecting all apps that are inside your docker network
  docker:
    watch: true
    network: proxy
    endpoint: "tcp://socket-proxy:2375"
    swarmModeRefreshSeconds: 15s
    exposedByDefault: false

  file:
    directory: /rules
    watch: true

# Using LetsEncrypt to generate ssl certs
certificatesResolvers:
  mydnschallenge:
    acme:
      email: ${USER_EMAIL}
      storage: ./letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        # Used to make sure the dns challenge is propagated to the rights dns servers
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        delayBeforeCheck: 10

# Enabling traefik dashboard UI
api:
  dashboard: true

# log level INFO|DEBUG|ERROR
log:
  level: INFO
