name: immich

x-app: &default
  restart: always
  environment: &environment
    TZ: America/Vancouver
  labels: &labels
    com.centurylinklabs.watchtower.enable: true
  security_opt:
    - no-new-privileges:true

services:
  immich:
    <<: *default
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION:?err}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - type: bind    # binding the redis password file
        source: ../authelia/secrets/REDIS_PASSWORD
        target: /secrets/REDIS_PASSWORD
        read_only: true
    labels:
      <<: *labels
      traefik.enable: true      # applying traefik reverse proxy
    env_file:
      - .env
    ports:
      - 2283:3001
    environment:
      <<: *environment
      REDIS_PASSWORD_FILE: /secrets/REDIS_PASSWORD
    networks:
      - secure
      - proxy
    depends_on:
      - postgresdb

  immich-machine-learning:
    <<: *default
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    networks:
      - secure
      - proxy

  postgresdb:
    <<: *default
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      <<: *environment
      POSTGRES_PASSWORD: ${DB_PASSWORD:?err}
      POSTGRES_USER: ${DB_USERNAME:?err}
      POSTGRES_DB: ${DB_DATABASE_NAME:?err}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./secrets:/secrets
    networks:
      - secure
      
  pgdbbackup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local
    env_file:
      - .env
    environment:
      <<: *environment
      POSTGRES_HOST: postgresdb
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@daily"
      BACKUP_DIR: /db_dumps
      BACKUP_KEEP_DAYS: 14
    volumes:
      - /mnt/user/backups/immich_dbdumps:/db_dumps
    depends_on:
      - postgresdb
    networks:
      - secure

volumes:
  pgdata:
  model-cache:
  
networks:
  proxy:
    external: true
  secure:
    external: true
