services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - ./jellyfin:/config:rw
      - ${MEDIA_DIR:?err}:/data/media:ro
      - ${TRANSCODE_DIR:?err}:/tmp:rw
    environment:
      TZ: America/Vancouver
      PGID: ${PGID:?err}
      PUID: ${PUID:?err}
      UMASK: ${UMASK:?err}
    labels:
      traefik.enable: true
      com.centurylinklabs.watchtower.enable: true
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    ports:
      - 5055:5055
    volumes:
      - ./jellyseerr:/app/config
    labels:
      traefik.enable: true
      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: America/Vancouver
      PGID: ${PGID:?err}
      PUID: ${PUID:?err}
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  proxy:
    external: true
