version: '3.9'

services:
  webserver:
    image: httpd:2.4
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ${APP_DIR}/data:/usr/local/apache2/htdocs/
    networks:
      - proxy
    labels:
      # Enabling traefik on this
      traefik.enable: true
      traefik.http.routers.webserver.rule: Host(`www.${DOMAIN}.com`)
      traefik.http.routers.webserver.entrypoints: https
      traefik.http.routers.webserver.tls: true
      traefik.http.routers.webserver.tls.certresolver: mydnschallenge
      # Watchtower Update
      com.centurylinklabs.watchtower.enable: true

networks:
  proxy:
    driver: bridge
    external: true
