version: '3.9'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - ${APP_DIR:?err}/jellyfin:/etc/jellyfin/config
      - ${MEDIA_DIR:?err}:/data:ro
      - ${APP_DIR:?err}/jellyfin:/cache
      - ${TRANSCODE_DIR:?err}:/transcode
    networks:
      - proxy
    environment:
      TZ: ${CONTAINER_TIME_ZONE:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
      UMASK: ${UMASK:?err}
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.entryPoints: https

      #com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    ports:
      - 5055:5055
    volumes:
      - ${APP_DIR:?err}/jellyseerr:/app/config
    labels:
      traefik.enable: true
      traefik.http.routers.jellyseerr.entryPoints: https

      #com.centurelinklabs.watchtower.enable: true
    environment:
      TZ: ${CONTAINER_TIME_ZONE:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true
