services:
  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 8282:8282
    labels:
      traefik.enable: true
      traefik.http.routers.adminer.middlewares: auth@file   # applies authelia security login
      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: America/Vancouver
    networks:
      - secure
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  secure:
    external: true
