services:
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8282:8282
    labels:
      traefik.enable: true
      traefik.http.routers.adminer.middlewares: auth@file
      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: America/Vancouver
    networks:
      - secure
    restart: unless-stopped

networks:
  secure:
    driver: bridge
    external: true
