http:
  middlewares:
    whitelist:
      ipWhiteList:
        sourceRange:
          - 127.0.0.1/32     # localhost
          - 192.168.50.1/24  # LAN subnet
          - 172.16.0.0/12    # Private IP range use by docker, enable to enable services access through VPN
