version: '3.9'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - ${APP_DIR:?err}/jellyfin:/etc/jellyfin/config
      - ${MEDIA_DIR:?err}:/media
      - ${APP_DIR:?err}/jellyfin:/cache
      - ${TRANSCODE_DIR:?err}:/transcode
    networks:
      - proxy   # change to your docker network name
    environment:
      TZ: ${CONTAINER_TIME_ZONE:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
      UMASK: ${UMASK:?err}
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.entryPoints: https

      # Watchtower Updater
      com.centurylinklabs.watchtower.enable: true
    restart: 'unless-stopped'

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    expose:
      - 7878
    volumes:
      - ${APP_DIR:?err}/radarr:/etc/radarr/config
      - ${MEDIA_DIR:?err}/movies:/media/movies
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.entryPoints: https
      traefik.http.routers.radarr.middlewares: auth@file

      # watchtower updater
      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: ${CONTAINER_TIME_ZONE:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
      UMASK: ${UMASK:?err}
    networks:
      - proxy   # change to your docker network name
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    expose:
      - 8989
    volumes:
      - ${APP_DIR:?err}/sonarr:/etc/sonarr/config
      - ${MEDIA_DIR:?err}/tvshows:/media/tvshows
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.entryPoints: https
      traefik.http.routers.sonarr.middlewares: auth@file

      # watchtower updater
      com.centurelinklabs.watchtower.enable: true
    environment:
      TZ: ${CONTAINER_TIME_ZONE:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
      UMASK: ${UMASK:?err}
    networks:
      - proxy   # change to your docker network name
    restart: unless-stopped

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    ports:
      - 5055:5055
    volumes:
      - ${APP_DIR:?err}/jellyseerr:/etc/jellyseerr/config
    labels:
      traefik.enable: true
      traefik.http.routers.request.entryPoints: https

      # watchtower updater
      com.centurelinklabs.watchtower.enable: true
    environment:
      TZ: ${CONTAINER_TIME_ZONE:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
    networks:
      - proxy   # change to your docker network name
    restart: unless-stopped

networks:
  proxy:    # defining your docker network name
    driver: bridge
    external: true
