###############################################################################
#                           Authelia Configuration                            #
###############################################################################
        #  All secrets and password are specficied in docker volumes  #
theme: dark

server:
  address: 'tcp://:9091/'
  disable_healthcheck: false
  tls:
    key: ''
    certificate: ''
    client_certificates: []
  buffers:
    read: 4096
    write: 4096
  timeouts:
    read: '6s'
    write: '6s'
    idle: '30s'
  endpoints:
    enable_pprof: false
    enable_expvars: false
    authz: {}	## See the dedicated "Server Authz Endpoints" configuration guide.

log:
  level: info
  file_path: "/var/log/crowdsec/authelia.log"
  keep_stdout: true

totp:
  disable: false
  issuer: authelia.com
  algorithm: sha1
  digits: 8
  period: 30
  skew: 1
  secret_size: 32

authentication_backend:
  refresh_interval: 5m
  password_reset:
    disable: false

  ldap:
    address: 'ldap://openldap'
    implementation: 'custom'
    timeout: '5s'
    start_tls: false
    tls:
      skip_verify: false
      minimum_version: 'TLS1.2'
      maximum_version: 'TLS1.3'
    base_dn: 'DC=nightowls,DC=pro'
    additional_users_dn: 'OU=Users'
    users_filter: '(&({username_attribute}={input})(objectClass=inetOrgPerson))'
    additional_groups_dn: 'OU=Groups'
    groups_filter: '(&(member={dn})(objectClass=groupOfNames))'
    user: 'cn=admin,dc=nightowls,dc=pro'
    attributes:
      username: 'uid'
      display_name: 'givenName'
      mail: 'mail'
      group_name: 'cn'

access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain:
        - "auth.nightowls.pro"
      policy: bypass
    ## bypass api / triggers
    - domain: "*.nightowls.pro"
      resources:
        - "^/api([/?].*)?$"
      policy: bypass
    ## two factor login for everyone
    - domain: "*.nightowls.pro"
      policy: two_factor

session:
  name: 'authelia_session'
  same_site: 'lax'
  expiration: '1h'
  inactivity: '5m'
  remember_me: '1M'
  cookies:
    - domain: 'nightowls.pro'
      authelia_url: 'https://auth.nightowls.pro'
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1d'
  redis:
    host: redis
    port: 6379
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0

regulation:
  max_retries: '4'
  find_time: '10m'
  ban_time: '12h'

password_policy:
  zxcvbn:
    enabled: true
    min_score: '4'

storage:
  mysql:
    address: 'tcp://mariadb:3306'
    database: 'autheliadb'
    username: 'authelia'
    timeout: 10s

notifier:
  disable_startup_check: false
  smtp:
    username: 'authelia.nightowls@gmail.com'
    address: 'submission://smtp.gmail.com:587'
    sender: 'authelia.nightowls@gmail.com'
    subject: "[Authelia] Nightowls Action Request"
    startup_check_address: 'test@authelia.com'
