###############################################################################
#                           Authelia Configuration                            #
###############################################################################
#  All secrets and password are specficied in docker volumes
theme: dark
default_redirection_url: https://auth.nightowls.duckdns.org/

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  buffers:
    read: 4096
    write: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: info

totp:
  disable: false
  issuer: authelia.com
  algorithm: sha1
  digits: 8
  period: 30
  skew: 1
  secret_size: 32

authentication_backend:
  refresh_interval: 5m
  password_reset:
    disable: false

  ldap:
    implementation: custom
    url: ldap://openldap
    timeout: 5s
    start_tls: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
      maximum_version: TLS1.3
    base_dn: DC=nightowls,DC=duckdns,DC=org
    additional_users_dn: OU=Users
    users_filter: (&({username_attribute}={input})(objectClass=inetOrgPerson))
    username_attribute: uid
    mail_attribute: mail
    display_name_attribute: givenName
    additional_groups_dn: OU=Groups
    groups_filter: (&(member={dn})(objectClass=groupOfNames))
    group_name_attribute: cn
    user: cn=admin,dc=nightowls,dc=duckdns,dc=org

access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain:
        - "auth.nightowls.duckdns.org"
      policy: bypass
    ## bypass api / triggers
    - domain: "*.nightowls.duckdns.org"
      resources:
        - "^/api([/?].*)?$"
      policy: bypass
    ## one factor login - catch all for admins
    - domain: "*.nightowls.duckdns.org"
      subject:
      - "group:admins"
      policy: two_factor

session:
  name: authelia_session
  domain: nightowls.duckdns.org
  same_site: lax
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 2M
  redis:
    host: redis
    port: 6379
    database_index: 0
    maximum_active_connections: 10
    minimum_idle_connections: 0

regulation:
  max_retries: 4
  find_time: 10m
  ban_time: 12h

password_policy:
  zxcvbn:
    enabled: true
    min_score: 4

storage:
  mysql:
    host: mariadb
    port: 3306
    database: autheliadb
    username: authelia
    timeout: 10s

notifier:
  disable_startup_check: false
  smtp:
    username: authelia.nightowls@gmail.comls -la
    host: smtp.gmail.com
    port: 587
    sender: authelia.nightowls@gmail.com
    subject: "[Authelia] You requested from Nightowls"
    startup_check_address: test@authelia.com
