services:
    crowdsec:   # crowdsec traefik-bouncer is referenced in traefiks service as a plugin 
        image: crowdsecurity/crowdsec:latest
        container_name: crowdsec
        expose:
            - 8080   # http api for bouncers
            #- 6060   # metrics endpoint for prometheus
            - 7422   # appsec waf endpoint
        ports:
            - 127.0.0.1:9876:8080   # port mapping for local firewall bouncers
        volumes:
            - ./acquis.yaml:/etc/crowdsec/acquis.yaml
            - ./crowdsec_config/data:/var/lib/crowdsec_config/data
            - ./crowdsec_config:/etc/crowdsec
            - /var/log/crowdsec:/var/log/crowdsec:ro  # all the logs in crowdsec folder using inside acquis.yaml
            - type: bind    # binding the single syslog file
              source: /var/log/syslog
              target: /var/log/syslog
              read_only: true
        environment:
            COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/appsec-generic-rules crowdsecurity/appsec-virtual-patching crowdsecurity/sshd crowdsecurity/linux crowdsecurity/base-http-scenarios LePresidente/authelia"
            TZ: America/Vancouver
            PGID: ${PGID:?err}
            PUID: ${PUID:?err}
        security_opt:
            - no-new-privileges:true
        networks:
            - proxy
        restart: always

networks:
  proxy:
    external: true
